In [1]:
import gym

In [2]:
env = gym.make('CartPole-v0')

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


/home/tom/work/library/gym/gym/__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
  warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')


In [4]:
env.reset()
for _ in range(1000):
    env.render()
    print(env.step(env.action_space.sample()))

(array([ 0.01090029,  0.15549364,  0.01198966, -0.32865213]), 1.0, False, {})
(array([ 0.01401016, -0.03979692,  0.00541662, -0.03221246]), 1.0, False, {})
(array([ 0.01321423,  0.15524694,  0.00477237, -0.32318148]), 1.0, False, {})
(array([ 0.01631916, -0.03994265, -0.00169126, -0.02899737]), 1.0, False, {})
(array([ 0.01552031, -0.2350403 , -0.00227121,  0.26315146]), 1.0, False, {})
(array([ 0.01081951, -0.43012976,  0.00299182,  0.55511716]), 1.0, False, {})
(array([ 0.00221691, -0.23504994,  0.01409416,  0.26337834]), 1.0, False, {})
(array([-0.00248409, -0.43037021,  0.01936173,  0.56047318]), 1.0, False, {})
(array([-0.01109149, -0.23552527,  0.03057119,  0.27395255]), 1.0, False, {})
(array([-0.015802  , -0.04085255,  0.03605024, -0.00893355]), 1.0, False, {})
(array([-0.01661905, -0.23647247,  0.03587157,  0.29490215]), 1.0, False, {})
(array([-0.0213485 , -0.43208698,  0.04176961,  0.59867913]), 1.0, False, {})
(array([-0.02999024, -0.62776771,  0.0537432 ,  0.9042209 ]), 1.

(array([-2.26642993, -1.92205187,  8.29205369,  7.28878374]), 0.0, True, {})
(array([-2.30487096, -1.68849872,  8.43782936,  7.70362956]), 0.0, True, {})
(array([-2.33864094, -1.82192112,  8.59190195,  7.8386065 ]), 0.0, True, {})
(array([-2.37507936, -1.58480661,  8.74867408,  8.29540649]), 0.0, True, {})
(array([-2.40677549, -1.72684816,  8.91458221,  8.31318739]), 0.0, True, {})
(array([-2.44131245, -1.49670439,  9.08084596,  8.7580138 ]), 0.0, True, {})
(array([-2.47124654, -1.27365276,  9.25600623,  9.17213136]), 0.0, True, {})
(array([-2.4967196 , -1.45224482,  9.43944886,  8.95743313]), 0.0, True, {})
(array([-2.52576449, -1.25848467,  9.61859752,  9.24372899]), 0.0, True, {})
(array([-2.55093419, -1.08260701,  9.8034721 ,  9.44597886]), 0.0, True, {})
(array([-2.57258633, -1.31253896,  9.99239168,  9.01682357]), 0.0, True, {})
(array([-2.59883711, -1.16958573, 10.17272815,  9.03956716]), 0.0, True, {})
(array([-2.62222882, -1.41768187, 10.3535195 ,  8.56679356]), 0.0, True, {})

(array([-7.10828009, -2.20549449, 23.54193787,  5.17766083]), 0.0, True, {})
(array([-7.15238998, -2.41195179, 23.64549109,  4.87752418]), 0.0, True, {})
(array([-7.20062902, -2.61430681, 23.74304157,  4.60987914]), 0.0, True, {})
(array([-7.25291515, -2.44875808, 23.83523916,  4.27596191]), 0.0, True, {})
(array([-7.30189032, -2.64407817, 23.92075839,  4.0719499 ]), 0.0, True, {})
(array([-7.35477188, -2.47052024, 24.00219739,  3.70525272]), 0.0, True, {})
(array([-7.40418228, -2.29263793, 24.07630245,  3.32557577]), 0.0, True, {})
(array([-7.45003504, -2.48058704, 24.14281396,  3.2083163 ]), 0.0, True, {})
(array([-7.49964678, -2.66794416, 24.20698029,  3.11675491]), 0.0, True, {})
(array([-7.55300567, -2.4821842 , 24.26931539,  2.71430006]), 0.0, True, {})
(array([-7.60264935, -2.29342117, 24.32360139,  2.3068406 ]), 0.0, True, {})
(array([-7.64851777, -2.4780619 , 24.3697382 ,  2.28521134]), 0.0, True, {})
(array([-7.69807901, -2.28600913, 24.41544243,  1.87381618]), 0.0, True, {})

(array([-10.47625949,  -0.76103297,  16.6659944 ,  -7.43288098]), 0.0, True, {})
(array([-10.49148015,  -0.62348749,  16.51733678,  -7.55473069]), 0.0, True, {})
(array([-10.5039499 ,  -0.48128554,  16.36624217,  -7.62037529]), 0.0, True, {})
(array([-10.51357561,  -0.71169649,  16.21383466,  -8.07363023]), 0.0, True, {})
(array([-10.52780954,  -0.93979409,  16.05236206,  -8.51538722]), 0.0, True, {})
(array([-10.54660542,  -0.77449381,  15.88205431,  -8.38126025]), 0.0, True, {})
(array([-10.5620953 ,  -0.98347423,  15.71442911,  -8.7409172 ]), 0.0, True, {})
(array([-10.58176478,  -0.78892756,  15.53961076,  -8.45100424]), 0.0, True, {})
(array([-10.59754333,  -0.96963417,  15.37059068,  -8.66896979]), 0.0, True, {})
(array([-10.61693602,  -0.74754425,  15.19721128,  -8.25729788]), 0.0, True, {})
(array([-10.6318869 ,  -0.90134399,  15.03206533,  -8.31483794]), 0.0, True, {})
(array([-10.64991378,  -0.66382759,  14.86576857,  -7.85296607]), 0.0, True, {})
(array([-10.66319033,  -0.80

(array([-7.57811383,  3.36605344,  2.77005678, -9.35429905]), 0.0, True, {})
(array([-7.51079276,  3.20829713,  2.5829708 , -9.46805234]), 0.0, True, {})
(array([-7.44662682,  3.45122551,  2.39360975, -9.0032271 ]), 0.0, True, {})
(array([-7.37760231,  3.32143554,  2.21354521, -8.94597583]), 0.0, True, {})
(array([-7.3111736 ,  3.2013236 ,  2.03462569, -8.8186355 ]), 0.0, True, {})
(array([-7.24714712,  3.45518182,  1.85825298, -8.38534264]), 0.0, True, {})
(array([-7.17804349,  3.33765179,  1.69054613, -8.15338817]), 0.0, True, {})
(array([-7.11129045,  3.5812936 ,  1.52747837, -7.81783407]), 0.0, True, {})
(array([-7.03966458,  3.81807407,  1.37112169, -7.53949032]), 0.0, True, {})
(array([-6.9633031 ,  3.68394762,  1.22033188, -7.2114257 ]), 0.0, True, {})
(array([-6.88962415,  3.90765766,  1.07610337, -7.05050788]), 0.0, True, {})
(array([-6.81147099,  4.12703625,  0.93509321, -6.94798296]), 0.0, True, {})
(array([-6.72893027,  4.34297312,  0.79613355, -6.90373121]), 0.0, True, {})

(array([  1.57660079,   3.86689635, -11.74670766,  -3.03158764]), 0.0, True, {})
(array([  1.65393872,   3.67853723, -11.80733942,  -2.62387488]), 0.0, True, {})
(array([  1.72750946,   3.86467024, -11.85981692,  -2.62409864]), 0.0, True, {})
(array([  1.80480287,   3.67274686, -11.91229889,  -2.21426256]), 0.0, True, {})
(array([  1.8782578 ,   3.47886203, -11.95658414,  -1.80458195]), 0.0, True, {})
(array([  1.94783504,   3.2835146 , -11.99267578,  -1.39600034]), 0.0, True, {})
(array([  2.01350534,   3.08712004, -12.02059578,  -0.98900696]), 0.0, True, {})
(array([  2.07524774,   2.89001652, -12.04037592,  -0.58369324]), 0.0, True, {})
(array([  2.13304807,   3.07565418, -12.05204979,  -0.67689975]), 0.0, True, {})
(array([  2.19456115,   2.87810783, -12.06558778,  -0.27428453]), 0.0, True, {})
(array([  2.25212331,   3.06408818, -12.07107347,  -0.37784638]), 0.0, True, {})
(array([  2.31340507,   2.86630445, -12.0786304 ,   0.02291315]), 0.0, True, {})
(array([  2.37073116,   2.66

(array([10.52479531,  5.18206668, -3.71048726,  8.72121969]), 0.0, True, {})
(array([10.62843665,  5.41864805, -3.53606286,  9.17857645]), 0.0, True, {})
(array([10.73680961,  5.26189634, -3.35249133,  9.07449644]), 0.0, True, {})
(array([10.84204754,  5.08708849, -3.17100141,  8.87964003]), 0.0, True, {})
(array([10.94378931,  4.89466217, -2.9934086 ,  8.59977029]), 0.0, True, {})
(array([11.04168255,  5.07674677, -2.8214132 ,  8.8264971 ]), 0.0, True, {})
(array([11.14321748,  4.85502535, -2.64488326,  8.41828449]), 0.0, True, {})
(array([11.24031799,  5.00863933, -2.47651757,  8.48075899]), 0.0, True, {})
(array([11.34049078,  5.14956748, -2.30690239,  8.46566453]), 0.0, True, {})
(array([11.44348213,  5.28047625, -2.1375891 ,  8.37962413]), 0.0, True, {})
(array([11.54909165,  5.40483288, -1.96999661,  8.23175372]), 0.0, True, {})
(array([11.65718831,  5.52635904, -1.80536154,  8.0317228 ]), 0.0, True, {})
(array([11.76771549,  5.28358756, -1.64472708,  7.66113638]), 0.0, True, {})

(array([20.99954194,  3.32669481, 10.6546728 ,  5.4253779 ]), 0.0, True, {})
(array([21.06607584,  3.48025353, 10.76318036,  5.22530703]), 0.0, True, {})
(array([21.13568091,  3.63548367, 10.8676865 ,  4.99283644]), 0.0, True, {})
(array([21.20839058,  3.7933093 , 10.96754323,  4.73143089]), 0.0, True, {})
(array([21.28425677,  3.95441839, 11.06217185,  4.44431959]), 0.0, True, {})
(array([21.36334514,  3.75551097, 11.15105824,  4.17082676]), 0.0, True, {})
(array([21.43845536,  3.9240256 , 11.23447477,  3.84122955]), 0.0, True, {})
(array([21.51693587,  4.09654221, 11.31129936,  3.49434446]), 0.0, True, {})
(array([21.59886671,  3.90686984, 11.38118625,  3.30321799]), 0.0, True, {})
(array([21.67700411,  4.08588111, 11.44725061,  2.92981062]), 0.0, True, {})
(array([21.75872173,  4.26829579, 11.50584683,  2.54586492]), 0.0, True, {})
(array([21.84408765,  4.08403458, 11.55676412,  2.42431109]), 0.0, True, {})
(array([21.92576834,  4.27096024, 11.60525035,  2.02618303]), 0.0, True, {})

(array([28.90483961,  2.91120261, 10.05714104,  5.88753972]), 0.0, True, {})
(array([28.96306366,  3.07530435, 10.17489184,  5.9123251 ]), 0.0, True, {})
(array([29.02456975,  2.85719761, 10.29313834,  5.4725448 ]), 0.0, True, {})
(array([29.0817137 ,  3.01616922, 10.40258923,  5.40220553]), 0.0, True, {})
(array([29.14203708,  3.17313526, 10.51063334,  5.28997643]), 0.0, True, {})
(array([29.20549979,  3.32924842, 10.61643287,  5.13903356]), 0.0, True, {})
(array([29.27208476,  3.48562856, 10.71921354,  4.95273246]), 0.0, True, {})
(array([29.34179733,  3.64328561, 10.81826819,  4.73441492]), 0.0, True, {})
(array([29.41466304,  3.80306507, 10.91295649,  4.48729664]), 0.0, True, {})
(array([29.49072434,  3.96561681, 11.00270242,  4.21442104]), 0.0, True, {})
(array([29.57003668,  4.13138455, 11.08699085,  3.9186561 ]), 0.0, True, {})
(array([29.65266437,  4.30061217, 11.16536397,  3.60271072]), 0.0, True, {})
(array([29.73867661,  4.47336241, 11.23741818,  3.26915262]), 0.0, True, {})

In [170]:
from collections import namedtuple
import random

Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward', 'done'))


class ReplayMemory(object):

    def __init__(self, capacity):
        self.capacity = capacity
        self.memory = []
        self.position = 0

    def push(self, *args):
        """Saves a transition."""
        if len(self.memory) < self.capacity:
            self.memory.append(None)
        args = [torch.tensor(x) for x in args]
        self.memory[self.position] = Transition(*args)
        self.position = (self.position + 1) % self.capacity

    def sample(self, batch_size):
        return random.sample(self.memory, batch_size)

    def __len__(self):
        return len(self.memory)

In [171]:
import torch.nn as nn
import torch.nn.functional as F
import torch

class DQN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(4, 4)
        self.fc2 = nn.Linear(4, 2)
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x
    

In [196]:
from tqdm import tqdm
import numpy as np
import torch.optim as optim

memory_length = 1000

policy_net = DQN()
target_net = DQN()
optimizer = optim.Adam(policy_net.parameters(), lr=0.01)
# Clopy the network
target_net.load_state_dict(policy_net.state_dict())
memory = ReplayMemory(10000)


n_episode = 1000
render_step = 1

BATCH_SIZE = 128
GAMMA = 0.99
EPS_START = 0.9
EPS_END = 0.1
EPS_DECAY = 20000
TARGET_UPDATE = 10

def get_eps(step):
    return max(EPS_END, EPS_END + step * (EPS_START - EPS_END) / EPS_DECAY)


for _ in tqdm(range(n_episode)):
    done = False
    old_obs = env.reset()
    old_obs = torch.from_numpy(old_obs).float()
    step = 0
    global_step = 0
    while not done:
        eps = get_eps(global_step)
        if True or np.random.uniform() < eps:
            action = env.action_space.sample()
        else:
            action = policy_net(old_obs)
        obs, reward, done, info = env.step(action)
        obs = torch.from_numpy(obs).float()
        memory.push(old_obs, action, obs_tensor,  reward, done)
        old_obs = obs
        step += 1
        global_step += 1
        if step % render_step == 0:
            env.render()
            
        # Training
        if len(memory) >= BATCH_SIZE:
            batch =  Transition(*zip(*memory.sample(BATCH_SIZE)))
            batch_state = torch.cat([x.unsqueeze(0) for x in batch.state])
            batch_action = torch.cat([x.unsqueeze(0) for x in batch.action])
            batch_reward = torch.cat([x.unsqueeze(0) for x in batch.reward])
            batch_done = torch.cat([x.unsqueeze(0) for x in batch.done])
            batch_next_state = torch.cat([x.unsqueeze(0) for x in batch.next_state])
            # Build State Action Value
            batch_output = policy_net(batch_state)
            state_action_values = batch_output.gather(1, batch_action.unsqueeze(1)).squeeze(1)
            # Build Target
            batch_target = target_net(batch_next_state)
            next_state_values = torch.zeros(BATCH_SIZE)
            batch_max = batch_target.max(1)[0].detach()
            next_state_values[batch_done] = batch_max[batch_done]
            target = batch_reward + GAMMA * next_state_values
            # Optimization
            loss = F.smooth_l1_loss(state_action_values, target)
            optimizer.zero_grad()
            loss.backward()
            for param in policy_net.parameters():
                param.grad.data.clamp_(-1, 1)
            optimizer.step()
        
        if global_step % TARGET_UPDATE == 0:
            target_net.load_state_dict(policy_net.state_dict())

100%|██████████| 1000/1000 [06:12<00:00,  2.68it/s]


In [162]:
torch.cat([torch.ones(3).unsqueeze(0), torch.ones(3).unsqueeze(0)]).shape

torch.Size([2, 3])

In [189]:
help(F.smooth_l1_loss)

Help on built-in function smooth_l1_loss:

smooth_l1_loss(...)
    smooth_l1_loss(input, target, size_average=True, reduce=True) -> Tensor
    
    Function that uses a squared term if the absolute
    element-wise error falls below 1 and an L1 term otherwise.
    
    See :class:`~torch.nn.SmoothL1Loss` for details.



In [190]:
help(pytorch.detach)

NameError: name 'pytorch' is not defined

In [169]:
torch.randn(3).max(0)[0]

tensor(2.3467)

In [92]:
obs_.float()

tensor([[-0.2590, -1.5937,  0.2239,  2.2517]])

In [99]:
transtions = memory.sample(3)

In [112]:
x = Transition(*zip(*transtions))

In [111]:
for i in x:
    print(i)
    break

(array([ 0.03294487,  0.41692597, -0.00334764, -0.50945142]), array([ 0.03827552,  0.02455782, -0.02828325, -0.11777853]), array([-0.01849946, -0.82277953,  0.06185798,  1.21121157]))


In [108]:
list(x)

[(array([ 0.03294487,  0.41692597, -0.00334764, -0.50945142]),
  array([ 0.03827552,  0.02455782, -0.02828325, -0.11777853]),
  array([-0.01849946, -0.82277953,  0.06185798,  1.21121157])),
 (1, 0, 0),
 (array([ 0.04128339,  0.61209492, -0.01353667, -0.80318742]),
  array([ 0.03876668, -0.17014772, -0.03063882,  0.16584879]),
  array([-0.03495505, -1.01864311,  0.08608221,  1.52261968])),
 (1.0, 1.0, 1.0)]

In [113]:
x

Transition(state=(array([ 0.03294487,  0.41692597, -0.00334764, -0.50945142]), array([ 0.03827552,  0.02455782, -0.02828325, -0.11777853]), array([-0.01849946, -0.82277953,  0.06185798,  1.21121157])), action=(1, 0, 0), next_state=(array([ 0.04128339,  0.61209492, -0.01353667, -0.80318742]), array([ 0.03876668, -0.17014772, -0.03063882,  0.16584879]), array([-0.03495505, -1.01864311,  0.08608221,  1.52261968])), reward=(1.0, 1.0, 1.0))

In [135]:
x = torch.ones(3, dtype=torch.long).unsqueeze(1)
y = torch.randn((3, 5))

In [136]:
y.gather(1, x)

tensor([[ 0.5968],
        [-0.0092],
        [ 1.6653]])

In [186]:
x.requires_grad

False

In [133]:
torch.eye(x)

TypeError: eye(): argument 'n' (position 1) must be int, not Tensor

In [134]:
help(torch.eye)

Help on built-in function eye:

eye(...)
    eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
    
    Args:
        n (int): the number of rows
        m (int, optional): the number of columns with default being :attr:`n`
        out (Tensor, optional): the output tensor
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
        requires_grad (bool, optional): If autograd should record operations on the
    
    Returns:
        Tensor: A 2-D tensor with ones on the diagonal and zeros elsewhere
    
    Example::
    
        >>> torch.eye(3)
        tensor([[ 1.,  0.,  0.],
                [ 0.,  1.,  0.],
                [ 0.,  0.,  1.]])



In [212]:
(1.1 ** 5 - 1) / 0.1 * 35746

218232.90460000018

In [209]:
1.1 ** 6

1.7715610000000008

In [213]:
np.log1p

<ufunc 'log1p'>

In [214]:
help(np.log1p)

Help on ufunc object:

log1p = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array

In [216]:
np.exp(np.log1p(3))

4.0